name: generate animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Action mantida que gera o Pac-man oficial
      - name: generate pacman-contribution-graph.svg
        uses: lowlighter/metrics@latest
        with:
          filename: pacman-contribution-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
