name: generate stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Gera os cards de estatísticas e linguagens em SVG
      - uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: Madu2201

      # Envia para a branch stats-output
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: stats-output
          build_dir: profile-summary-card-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
